### ISSUE TITLE
Proposta de melhoria

### ISSUE THREAD

**Issue by leandrosantoss** [nfephp-org/sped-nfse-egoverne#11]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [ ] bug
  - [x] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

Achei que a assinatura do método Tools:consultarNfse ficou muito complexa, em momentos recebe valores e em outros xml (intermediario).

Proponho a mudança para receber o range de datas e o objeto Rps contendo o resto das informações, sendo possível aplicar as validações para montagem do XML.

**De:**
@param $dini => Data de inicio
@param $dfim => Data de fim
@param null $tomadorCnpj => CNPJ do tomador
@param null $tomadorCpf => CPF do tomador
@param null $tomadorIM => IM do tomador
@param null $numeroNFSe => Numero da NF
@param null $intermediario => XML do intermediador

**Para:**
@param $dini => Data de inicio
@param $dfim => Data de Fim
@param $rps => Rps contendo o restante das informações necessarias

O que acham?

**Comment by robmachado** [comment]
Eu já ia questionar isso !! A entrada de parâmetros nesse caso é melhor fazer por stdClass.
E nunca em hipótese alguma deveria receber um XML como parâmetro, sempre devem ser recebidos  dados simples (dentro do stdClass) apenas int, float, boolean ou string.

**Comment by leandrosantoss** [comment]
Concordo contigo, na verdade esse método já existia.

Concorda com a assinatura? (data_inicio, data_fim, Rps)

Vou alterar ok?

**Comment by robmachado** [comment]
veja seria algo como 
$std->data_inicial = '2020-12-12';
$std->data_final = "2020-12-31';
$std->tomador->cnpj = "12345678901234";
etc...

**Comment by leandrosantoss** [comment]
Show, farei assim.

Obrigado!

**Comment by leandrosantoss** [comment]
Melhoria efetuada no pull request #12 

Obrigado
